### ISSUE TITLE
MPI mesh library is only for Python > 3.6 while this repo is using Python2.7

### ISSUE THREAD

**Issue by mikecheninoulu** [kzhou23/shape_pose_disent#1]
Hi, thanks for your great work. 

I have a problem when reproducing your work that, MPI mesh library is only for Python > 3.6 while this repo is using Python2.7. 

So after I installed MPI mesh lib with python3, I cannot run this code. Are you using the old Python2 version of MPI mesh lib?

**Comment by kzhou23** [comment]
Hi! When I first started working on this project, MPI Mesh library only supported Python 2. You can try reverting to commit 1761d544686b3735991954947a8befa759891eb4, which seems to be the last version on Python 2.

**Comment by mikecheninoulu** [comment]
Thanks for your fast reply, I will try to use it to figure it out.
