### ISSUE TITLE
what edge weights are you using in the arap?

### ISSUE THREAD

**Issue by chaneyddtt** [kzhou23/shape_pose_disent#5]
Hi, thanks for your great work. I could not figure out what edge weights you are using in the arap constraint, could you please give a hint on this?

**Comment by kzhou23** [comment]
Hi, I simply use uniform weights.

**Comment by chaneyddtt** [comment]
Thanks a lot for your quickly reply. Did you try the cotangent weight from the original arap paper? and is there any difference between the uniform weight and the cotangent weight?

**Comment by kzhou23** [comment]
I've tried to use cotangent weights but did not observe perceivable differences. Uniform weight is also less computationally expensive.

**Comment by chaneyddtt** [comment]
Got you, thanks a lot.
