### ISSUE TITLE
SVD results of S

### ISSUE THREAD

**Issue by s0rrymaker77777** [kzhou23/shape_pose_disent#6]
Hi, 

Thank you for your work and codes. I notice that you may use the wrong u, v of SVD in lines 96 and 97 of arap.py. Thank you.

**Comment by kzhou23** [comment]
The naming of variables might cause some confusion here. U an v are actually SVD components of S, while in L95 I run SVD on S transposed. Hope it answers your question.

**Comment by ChaoyueSong** [comment]
Thank you for your reponse! I think I got it.

**Comment by s0rrymaker77777** [comment]
Thank you for your reponse! I think I got it.
